language: go
sudo: required
go:
- 1.6.0
env:
  matrix:
  - GIMME_OS=windows GIMME_ARCH=amd64
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=linux GIMME_ARCH=386
  - GIMME_OS=darwin GIMME_ARCH=amd64
  global:
    secure: P6nmw2g+2Pt/lH/6fL4z2mwOcq1sMjb1jQhlW4zF7kFHu6pMWYGfLZCl0GhYs3znut5QwGAKBqUbeRQI15qciKQfKGCVg7VzF9PbgucJJVSZG3anRsfE1FrjJTDaDoINrOOBfe6pvjVFKFflxuNqJovLEj32ke7yHxqDdiTQmKkWWMTi+0+s5ZdEn0s7/EklWZwocwz4VbYeEbIpvpJHEOXjAY+8juyGWt9tFXWEPD/bQMpxPiioUYDXfs9gT9tRFmTnTWwZOUyA9dVwWIZSr9Q72OBUYop3RYNgabTf8aAmWwsf/SrZAWUy8UbdItgUVKcNZQQ1dEN1oRnDZ8artTnk1M0L1Nqd1wsEWlRNT65jqe+sx7iJJLdeKLijDFBq3cdT8mYW0v5fj9mBlNE7ZEgmkexAjqGFq7MklFoNzWfjQfe8zHvndDMdgnKxqzb7/1KCkX6DFVxS8qdoUeLdZgZn0IvKH9TADAUg8/BdpYcT7bqG78o4jHRwRDQTZkxpKqFxbisObbNIcSMvyJZxBXf94kuwq0qn5ce+9/nzJCghEeZRUlshV85VGDtMYpoqZYGrMzEhbQ3Eaz/3/P8HlYbcq6iHAaVKixi0mmlvbENl7oRtWvdCJEH0AndYpCGJWKlzVtBIlARjJCKFtik7VU4atacbxQHDSDQiiomlrbM=
after_script:
- ls -l ../../../../bin
before_install:
- curl -o gimme -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
- chmod u+x gimme
- unset GOROOT GOTOOLDIR
- eval "$(./gimme 1.5)"
- go version
- go env
before_script:
- go get -d -v ./...
script:
- go build -v ./...
deploy:
  skip_cleanup: true
  file: bintray_descriptors/${GIMME_OS}_${GIMME_ARCH}.json
  provider: bintray
  user: uriahl
